### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by webysther** [alexphelps/server-error-pages#9]
Hi, great job! :dancer: 

I can suggest few things?

- [ ] Release a version using semantic version with compiled html only
- [ ] Provide dockerfile sample for apache/nginx use (maybe i can help with this)
- [ ] Change structure to support translated PR

**Comment by georgesuba** [comment]
A dockerfile for - error pages - huh? Rest you have in git...

**Comment by webysther** [comment]
Yeap, for sample working of apache/nginx. But a comment with section works like here https://github.com/AndiDittrich/HttpErrorPages#nginx-integration

**Comment by webysther** [comment]
Express concepts to all level of developers with working ideias is the best, not everyone can provide that.
